#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MASUnit.Android.MSSO.Resource", IsApplication=true)]

namespace MASUnit.Android.MSSO
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::MASUnit.Android.MSSO.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::MASUnit.Android.MSSO.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::MASUnit.Android.MSSO.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::MASUnit.Android.MSSO.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::MASUnit.Android.MSSO.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::MASUnit.Android.MSSO.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::MASUnit.Android.MSSO.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::MASUnit.Android.MSSO.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::MASUnit.Android.MSSO.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::MASUnit.Android.MSSO.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::MASUnit.Android.MSSO.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::MASUnit.Android.MSSO.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::MASUnit.Android.MSSO.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::MASUnit.Android.MSSO.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::MASUnit.Android.MSSO.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::MASUnit.Android.MSSO.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::MASUnit.Android.MSSO.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::MASUnit.Android.MSSO.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::MASUnit.Android.MSSO.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::MASUnit.Android.MSSO.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::MASUnit.Android.MSSO.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::MASUnit.Android.MSSO.Resource.Layout.test_suite;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int scim_operators = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ca_logo = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090001
			public const int OptionHostName = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int OptionPort = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int OptionRemoteServer = 2131296256;
			
			// aapt resource value: 0x7f090010
			public const int OptionsButton = 2131296272;
			
			// aapt resource value: 0x7f09000b
			public const int ResultFullName = 2131296267;
			
			// aapt resource value: 0x7f09000d
			public const int ResultMessage = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int ResultResultState = 2131296268;
			
			// aapt resource value: 0x7f09000a
			public const int ResultRunSingleMethodTest = 2131296266;
			
			// aapt resource value: 0x7f09000e
			public const int ResultStackTrace = 2131296270;
			
			// aapt resource value: 0x7f090006
			public const int ResultsFailed = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int ResultsId = 2131296259;
			
			// aapt resource value: 0x7f090007
			public const int ResultsIgnored = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int ResultsInconclusive = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int ResultsMessage = 2131296265;
			
			// aapt resource value: 0x7f090005
			public const int ResultsPassed = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int ResultsResult = 2131296260;
			
			// aapt resource value: 0x7f09000f
			public const int RunTestsButton = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int TestSuiteListView = 2131296273;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int options = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int results = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int test_result = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int test_suite = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int ormlite_config = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int acc_name = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int attempting_to_connect = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int client_already_connected = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int client_already_disconnected = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int connect_error = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int connected = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int connection_attempt = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int connection_lost = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int could_not_connect = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int could_not_disconnect = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int could_not_publish = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int could_not_subscribe = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int could_not_unsubscribe = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int delivery_failed = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int delivery_succeeded = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int disconnected = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int login_not_connected_error = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int published = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int resources = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int subscribe_success = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int subscribed = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int unsubscribed = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int uri_create_failed = 2131230743;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int massharedauthenticator = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mastest = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int prefs = 2131034114;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
