#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MASUnit3.Droid.Standard.Runner.Resource", IsApplication=true)]

namespace MASUnit3.Droid.Standard.Runner
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Nunit.Runner.Resource.String.ApplicationName = global::MASUnit3.Droid.Standard.Runner.Resource.String.ApplicationName;
			global::Nunit.Runner.Resource.String.Hello = global::MASUnit3.Droid.Standard.Runner.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::MASUnit3.Droid.Standard.Runner.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::MASUnit3.Droid.Standard.Runner.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::MASUnit3.Droid.Standard.Runner.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::MASUnit3.Droid.Standard.Runner.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int scim_operators = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ca_logo = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int myButton = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int ormlite_config = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080019
			public const int ApplicationName = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int Hello = 2131230744;
			
			// aapt resource value: 0x7f080000
			public const int acc_name = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int attempting_to_connect = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int client_already_connected = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int client_already_disconnected = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int connect_error = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int connected = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int connection_attempt = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int connection_lost = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int could_not_connect = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int could_not_disconnect = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int could_not_publish = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int could_not_subscribe = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int could_not_unsubscribe = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int delivery_failed = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int delivery_succeeded = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int disconnected = 2131230736;
			
			// aapt resource value: 0x7f08001a
			public const int hello = 2131230746;
			
			// aapt resource value: 0x7f080011
			public const int login_not_connected_error = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int published = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int resources = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int subscribe_success = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int subscribed = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int unsubscribed = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int uri_create_failed = 2131230743;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int massharedauthenticator = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mastest = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int prefs = 2131034114;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
